# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  admin_name_too: Second User
  admin_email_too: loser@example.com
  admin_password_too: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 56022d492ce1d3bc919bbf19a7f433912a7dd2e89f5f6904baa54b00d6b8c6a1c28c02acc9e651473647d079050e1538153a83efad93c4e9ab664acceb42861a

test:
  domain_name: example.com 
  secret_key_base: d34c6f66aaf58a8d3649d04cb6a5a05124095c81ba8fc0f64dd426c72c31b417ab4e97ed834f8c8dc04bd580d358a5533ec032bc502b1ce4d06a1a60f028e9c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["NAME1"] %>
  admin_email: <%= ENV["USER1"] %>
  admin_password: <%= ENV["PASS1"] %>
  admin_name_too: <%= ENV["NAME2"] %>
  admin_email_too: <%= ENV["USER2"] %>
  admin_password_too: <%= ENV["PASS2"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
